homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 44.0991
  longitude: -93.2220
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 352.65
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
    api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

recorder:
    purge_keep_days: 14
    purge_interval: 5
    

# Track the sun
sun:

wink:

# Weather Prediction
sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "F"
    value_template: '{{ (value | multiply(0.001) * 1.8 + 32) | round(1) }}'
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

# Text to speech
tts:
  platform: google

group: !include groups.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

ecobee:
    api_key: !secret ecobee_api_key